server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          default-label: main
          username: ${USERNAME}
          password: ${TOKEN}


management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans